### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TheDCM15** [AnthonyMichaelTDM/DRG-Save-Editor#43]
**Describe the bug**
PS C:\Users\User\Downloads\DRG-Save-Editor-master> python "C:\Users\User\Downloads\DRG-Save-Editor-master\src\main\python\main.py"
Traceback (most recent call last):
  File "C:\Users\User\Downloads\DRG-Save-Editor-master\src\main\python\main.py", line 19, in <module>
    from definitions import (GUID_RE, MAX_BADGES, PROMO_RANKS, RANK_TITLES, RESOURCE_GUIDS,
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\User\Downloads\DRG-Save-Editor-master\src\main\python\definitions.py", line 9, in <module>
    XP_TABLE: list[int] = [
TypeError: 'type' object is not subscriptable

**To Reproduce**
the pip install worked, but the python command isn't working and opening the save editor. I downloaded the python from microsoft store as told. Anything else i might be doing wrong?

**Comment by bbeenn1** [comment]
You may need to make sure you are using Python 3.10
